import pandas as pd

# Lista de especialidades com o Nível 1
especialidades = [
    "Acampamento (Nível 1)",
    "Acampamento de mínimo impacto (Nível 1)",
    "Administração (Nível 1)",
    "Aeromodelismo (Nível 1)",
    "Agricultura (Nível 1)",
    "Alfabetização (Nível 1)",
    "Almoxarifado (Nível 1)",
    "Anatomia humana (Nível 1)",
    "Animação da fé (Nível 1)",
    "Animais peçonhentos (Nível 1)",
    "Anime (Nível 1)",
    "Aquariofilia (Nível 1)",
    "Arco e flecha (Nível 1)",
    "Arqueologia (Nível 1)",
    "Arquitetura (Nível 1)",
    "Arte da marinharia (Nível 1)",
    "Arte digital (Nível 1)",
    "Arte em origami (Nível 1)",
    "Artes cênicas (Nível 1)",
    "Arte gráficas (Nível 1)",
    "Artes marciais (Nível 1)",
    "Artesanato (Nível 1)",
    "Astronáutica (Nível 1)",
    "Astronomia (Nível 1)",
    "Automobilismo rádio controlado (Nível 1)",
    "Babá (Nível 1)",
    "Barismo (Nível 1)",
    "Basquetebol (Nível 1)",
    "Bateria (Nível 1)",
    "Biblioteconomia (Nível 1)",
    "Biologia (Nível 1)",
    "Bolsa de valores (Nível 1)",
    "Boxe (Nível 1)",
    "Braille (Nível 1)",
    "Budismo (Nível 1)",
    "Canoagem (Nível 1)",
    "Canto (Nível 1)",
    "Capoeira (Nível 1)",
    "Carpintaria (Nível 1)",
    "Cartografia (Nível 1)",
    "Churrasco (Nível 1)",
    "Ciclismo (Nível 1)",
    "Cidadania do mundo (Nível 1)",
    "Ciências da terra (Nível 1)",
    "Cinefilia (Nível 1)",
    "Civismo (Nível 1)",
    "Coleções (Nível 1)",
    "Comédia (Nível 1)",
    "Comércio exterior (Nível 1)",
    "Compostagem (Nível 1)",
    "Comunicações (Nível 1)",
    "Confeitaria (Nível 1)",
    "Construção civil (Nível 1)",
    "Contabilidade (Nível 1)",
    "Corrida de orientação (Nível 1)",
    "Corrida de rua (Nível 1)",
    "Cosplay (Nível 1)",
    "Costura (Nível 1)",
    "Criação de animais de estimação (Nível 1)",
    "Criptografia (Nível 1)",
    "Cubo mágico (Nível 1)",
    "Cuidados bucais (Nível 1)",
    "Cuidados com idosos (Nível 1)",
    "Culinária (Nível 1)",
    "Culinária mateira (Nível 1)",
    "Culinária vegetariana (Nível 1)",
    "Cultura brasileira (Nível 1)",
    "Dança (Nível 1)",
    "Dança folclórica (Nível 1)",
    "Decoração (Nível 1)",
    "Defesa civil (Nível 1)",
    "Defesa nacional (Nível 1)",
    "Desportos inclusivos (Nível 1)",
    "DJ (Nível 1)",
    "Dublagem (Nível 1)",
    "E-sports (Nível 1)",
    "Echolink (Nível 1)",
    "Ecumenismo (Nível 1)",
    "Educação financeira (Nível 1)",
    "Egiptologia (Nível 1)",
    "Eletrônica (Nível 1)",
    "Empreendedorismo (Nível 1)",
    "Encadernação (Nível 1)",
    "Energia (Nível 1)",
    "Engenharia (Nível 1)",
    "Engenharia aeronáutica (Nível 1)",
    "Entomologia (Nível 1)",
    "Entrega de mensagens (Nível 1)",
    "Escalada (Nível 1)",
    "Esgrima (Nível 1)",
    "Espeleoturismo (Nível 1)",
    "Estilismo (Nível 1)",
    "Estudos da bíblia (Nível 1)",
    "Estudos desportivos (Nível 1)",
    "Etiqueta (Nível 1)",
    "Excursões (Nível 1)",
    "Faixa do cidadão (Nível 1)",
    "Ferramentas de corte (Nível 1)",
    "Fiscalização de pátio de aeródromo (Nível 1)",
    "Fogo de conselho (Nível 1)",
    "Fotografia (Nível 1)",
    "Fotografia digital (Nível 1)",
    "Futebol (Nível 1)",
    "Futebol de mesa (Nível 1)",
    "Gaão (Nível 1)",
    "Garçom (Nível 1)",
    "Genealogia (Nível 1)",
    "Geocaching (Nível 1)",
    "Geografia (Nível 1)",
    "Geologia (Nível 1)",
    "Ginástica (Nível 1)",
    "Ginástica rítmica (Nível 1)",
    "GPS (Nível 1)",
    "Grafite (Nível 1)",
    "Handebol (Nível 1)",
    "Herpetologia (Nível 1)",
    "Hidrografia (Nível 1)",
    "Hipismo (Nível 1)",
    "Hipismo rural (Nível 1)",
    "História aeroespacial (Nível 1)",
    "História brasileira (Nível 1)",
    "História da arte (Nível 1)",
    "História da igreja (Nível 1)",
    "História do escotismo (Nível 1)",
    "História local (Nível 1)",
    "História marítima (Nível 1)",
    "História mundial (Nível 1)",
    "Horticultura (Nível 1)",
    "HQ (Nível 1)",
    "Ictiologia (Nível 1)",
    "Inclusão (Nível 1)",
    "Informações turísticas (Nível 1)",
    "Informática (Nível 1)",
    "Internet (Nível 1)",
    "Invenção (Nível 1)",
    "Investigação (Nível 1)",
    "Ioiô (Nível 1)",
    "Jardinagem (Nível 1)",
    "Jogos de cartas colecionáveis (Nível 1)",
    "Jogos de tabuleiro (Nível 1)",
    "Jornalismo (Nível 1)",
    "Leis (Nível 1)",
    "Leitura (Nível 1)",
    "Lenhador (Nível 1)",
    "Libras (Nível 1)",
    "Licenciatura (Nível 1)",
    "Lides campeiras (Nível 1)",
    "Línguas (Nível 1)",
    "Literatura (Nível 1)",
    "Liturgia (Nível 1)",
    "Mágica e ilusionismo (Nível 1)",
    "Malabares (Nível 1)",
    "Manicure (Nível 1)",
    "Manutenção elétrica (Nível 1)",
    "Maquete (Nível 1)",
    "Maquiagem (Nível 1)",
    "Marcenaria (Nível 1)",
    "Marinharia (Nível 1)",
    "Matemática (Nível 1)",
    "Mecânica aérea (Nível 1)",
    "Mecânica de automóveis (Nível 1)",
    "Mecânica de motor de popa (Nível 1)",
    "Meliponicultura (Nível 1)",
    "Mergulho autônomo (Nível 1)",
    "Mergulho livre (Nível 1)",
    "Meteorologia (Nível 1)",
    "Microbiologia (Nível 1)",
    "Mineralogia (Nível 1)",
    "Minhocultura (Nível 1)",
    "Missionário (Nível 1)",
    "Mitologia (Nível 1)",
    "Montanhismo (Nível 1)",
    "Mountain bike (Nível 1)",
    "Multimídia (Nível 1)",
    "Musculação (Nível 1)",
    "Museologia (Nível 1)",
    "Música (Nível 1)",
    "Natação (Nível 1)",
    "Navegação aérea (Nível 1)",
    "Numismática (Nível 1)",
    "Nutrição (Nível 1)",
    "Observação aérea (Nível 1)",
    "Oceanologia (Nível 1)",
    "Oratória (Nível 1)",
    "Ornitologia (Nível 1)",
    "Paisagismo (Nível 1)",
    "Paleontologia (Nível 1)",
    "Paraquedismo (Nível 1)",
    "Le Parkour (Nível 1)",
    "Patinação (Nível 1)",
    "Pesca (Nível 1)",
    "Pintura (Nível 1)",
    "Pintura e desenho artístico (Nível 1)",
    "Pintura em tela (Nível 1)",
    "Pioneiria (Nível 1)",
    "Pipas (Nível 1)",
    "Planador (Nível 1)",
    "Plantas medicinais (Nível 1)",
    "Plastimodelismo (Nível 1)",
    "Poesia (Nível 1)",
    "Prática desportiva (Nível 1)",
    "Prevenção a fake news (Nível 1)",
    "Prevenção ao alcoolismo (Nível 1)",
    "Prevenção ao bullying (Nível 1)",
    "Prevenção ao crime (Nível 1)",
    "Prevenção ao uso de drogas (Nível 1)",
    "Prevenção de incêndio (Nível 1)",
    "Prevenção em saúde (Nível 1)",
    "Primeiros socorros (Nível 1)",
    "Produção áudio visual (Nível 1)",
    "Produção de laticínios (Nível 1)",
    "Programação (Nível 1)",
    "Propaganda e marketing (Nível 1)",
    "Proteção animal (Nível 1)",
    "Proteção de animais silvestres (Nível 1)",
    "Quebra-cabeças (Nível 1)",
    "Química (Nível 1)",
    "Radioamadorismo (Nível 1)",
    "Radioescuta (Nível 1)",
    "Rastreamento (Nível 1)",
    "Reciclagem (Nível 1)",
    "Recreação infantil (Nível 1)",
    "Remo (Nível 1)",
    "Reparos domésticos (Nível 1)",
    "Reparos navais (Nível 1)",
    "Road bike (Nível 1)",
    "Robótica (Nível 1)",
    "Rock (Nível 1)",
    "RPG (Nível 1)",
    "Salvamento (Nível 1)",
    "Saneamento ambiental (Nível 1)",
    "Secretariado (Nível 1)",
    "Segurança (Nível 1)",
    "Segurança aérea (Nível 1)",
    "Segurança doméstica (Nível 1)",
    "Segurança no mar (Nível 1)",
    "Segurança no trabalho (Nível 1)",
    "Segurança no trânsito (Nível 1)",
    "Segurança pública (Nível 1)",
    "Serralheria (Nível 1)",
    "Simulação aérea (Nível 1)",
    "Sinalização (Nível 1)",
    "Skateboard (Nível 1)",
    "Slackline (Nível 1)",
    "Slime (Nível 1)",
    "Sobrevivência (Nível 1)",
    "Sobrevivência no mar (Nível 1)",
    "Socorrismo (Nível 1)",
    "Softbol (Nível 1)",
    "Stand up paddle (Nível 1)",
    "Surf (Nível 1)",
    "Tecido acrobático (Nível 1)",
    "Técnica aeronáutica (Nível 1)",
    "Técnicas de sapa (Nível 1)",
    "Técnicas verticais (Nível 1)",
    "Tênis (Nível 1)",
    "Tênis de mesa (Nível 1)",
    "Topografia (Nível 1)",
    "Trabalho voluntário (Nível 1)",
    "Tradições (Nível 1)",
    "Tradições indígenas (Nível 1)",
    "Transporte ferroviário (Nível 1)",
    "Triatlo (Nível 1)",
    "Vela (Nível 1)",
    "Vendas (Nível 1)",
    "Vídeo maker (Nível 1)",
    "Videogame (Nível 1)",
    "Vigilância epidemiológica (Nível 1)",
    "Vitrines (Nível 1)",
    "Voleibol (Nível 1)",
    "Web design (Nível 1)",
    "Xadrez (Nível 1)",
    "Yoga (Nível 1)",
    "Zoobotânica (Nível 1)"
]

df = pd.DataFrame(especialidades, columns=["Especialidades"])

# Salvar o DataFrame em um arquivo Excel
df.to_excel("especialidades1.xlsx", index=False)

print("Arquivo Excel criado com sucesso!")